### PR TITLE
WIP: raise async exceptions

### PR DESCRIPTION
**Pull request by considerate**

### CODE REVIEW

**Review by jamesdbrock — APPROVED** [review]
Good idea

**Comment by considerate** [comment]
@jamesdbrock Currently the program hangs when the exceptions are raised so this shouldn't be merged in its current state.

**Comment by considerate** [comment]
@jamesdbrock Would it make sense to pick this up again or is this irrelevant now?

**Comment by jamesdbrock** [comment]
I don't think it's irrelevant, if this is the semantics that we want then it's worth doing.

Right now what we have is “if an exception is thrown in the coroutine then that exception pops the coroutine stack and then stops.”

This PR introduces “if a non-`CancelledError` exception is thrown in the coroutine then it pops the coroutine stack and then propagates to the main event loop.” Which means the whole app will halt, I think, right? Because there is no other opportunity to catch that exception.

Can you think of an example case where this PR behavior is clearly better?

If we just want to halt the `App` then currently the best explicit way to do that is [`use_stop`](https://pyedifice.github.io/stubs/edifice.use_stop.html#edifice.use_stop).

**Comment by jamesdbrock** [comment]
So the reason to do this PR would be so that async Tasks would fail obviously instead of failing silently, and that would be a better developer experience?

**Comment by considerate** [comment]
@jamesdbrock If I remember correctly, the reason for not just letting the async task swallow the errors is that errors weren't properly reported but it caused crashes and the application to hang.

I don't know if there's a case now where such behavior occurs so trying to be more explicit about raising the errors in the engine if a task dies might no longer be necessary.

**Comment by jamesdbrock** [comment]
I just tested raising an uncaught `ValueError` in a `use_async` Task and it seems to behave the correct way: The Task ends and the rest of the App is fine. https://github.com/pyedifice/pyedifice/commit/bca91f64aca46a35f7ba21be9b49a4287896c8a5

**Pull request closed without merging**
